version: "3"

interval: "500ms" # Interval for --watch mode
set: [e, u, pipefail]

vars:
  OUTPUT_FILE: 'dist/driebit_search_page.js'

tasks:
  default:
    deps: [build]

  build:
    cmds:
      - pwd
      - mkdir -p dist
      - task: "{{if .DEBUG}}elm-debug{{else}}elm-optimized{{end}}"

  elm-debug:
    cmds:
      - elm make --debug src/SearchPage.elm --output {{.OUTPUT_FILE}}

  elm-optimized: |
    elm make src/SearchPage.elm --optimize --output /tmp/elm.js
    uglifyjs /tmp/elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output {{.OUTPUT_FILE}}

  analyse:
    cmds:
      - elm-analyse --serve src

  format:
    cmds:
      - elm-format --yes src
      - elm-format --yes tests

  test: elm-test